owner: arcaptcha 
repo: ARCaptcha-monitoring

sites:
  - name: ARCaptcha
    url: https://arcaptcha.co
  - name: ARCaptcha widget
    url: https://widget.arcaptcha.co/1/api.js
  - name: ARCaptcha API
    url: https://api.arcaptcha.co
    expectedStatusCodes:
      - 404


status-website:
  theme: night
  cname: status.arcaptcha.ir
  favicon: https://arcaptcha.ir/favicon.ico
  # baseUrl: /your-repo-name
  logoUrl: https://arcaptcha.ir/_nuxt/023053fecdcdf20e40bdc993c754d487.svg
  name: ARCaptcha
  introTitle: "ARCaptcha"
  introMessage: ARCaptcha Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
