# Change these first
owner: arcaptcha # Your GitHub organization or username, where this repository lives
repo: ARCaptcha-monitoring # The name of this repository

sites:
  - name: ARCaptcha
    url: https://arcaptcha.ir
  - name: ARCaptcha widget
    url: https://widget.arcaptcha.ir/1/api.js


status-website:
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.arcaptcha.ir
  # baseUrl: /your-repo-name
  logoUrl: https://arcaptcha.ir/_nuxt/023053fecdcdf20e40bdc993c754d487.svg
  name: ARCaptcha
  introTitle: "ARCaptcha"
  introMessage: ARCaptcha Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
